---
title: Proceedings of Machine Learning Research
booktitle: Proceedings of the Fifth Conference on Causal Learning and Reasoning
shortname: CLeaR
year: '2026'
volume: '323'
start: 2026-04-06
end: 2026-04-08
published: 2026-07-05
conference_number: '5'
publisher: PMLR
series: Proceedings of Machine Learning Research
layout: proceedings
issn: 2640-3498
id: CLeaR2026
month: 0
tex_title: Proceedings of the Fifth Conference on Causal Learning and Reasoning
cycles: false
bibtex_editor: Mazaheri, Bijan and Hanson, Niels Richard
editor:
- given: Bijan
  family: Mazaheri
- given: Niels Richard
  family: Hanson
description: |
  Proceedings of the Fifth Conference on Causal Learning and Reasoning
    Held in Broad Institute of MIT and Harvard, Cambridge, USA on 06-08 April 2026

  Published as Volume 323 by the Proceedings of Machine Learning Research on 05 July 2026.

  Volume Edited by:
    Bijan Mazaheri
    Niels Richard Hanson

  Series Editors:
    Neil D. Lawrence
date_str: 06--08 Apr
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v323"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v323
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v323
email: ''
conference:
  name: Causal Learning and Reasoning
  url: https://www.cclear.cc/2026
  location: Broad Institute of MIT and Harvard, Cambridge, USA
  dates:
  - 2026-04-06
  - 2026-04-07
  - 2026-04-08
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: clear26-v323_clean.bib
# Site settings
# Original source:  clear26-v323_clean.bib